# Generated by Django 5.2 on 2025-04-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workerprofile",
            name="services",
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_services",
                to="core.service",
            ),
        ),
    ]
